name: sublime-merge
version: "2091"
summary: Meet a new Git Client, from the makers of Sublime Text
base: core18
description: |
  Meet a new Git Client, from the makers of Sublime Text.

architectures:
  - build-on: amd64
  - build-on: arm64

grade: stable
confinement: classic

apps:
  sublime-merge:
    command: opt/sublime_merge/sublime_merge
    desktop: opt/sublime_merge/sublime_merge.desktop
    aliases: [smerge]

parts:
  sublime-merge:
    source: https://download.sublimetext.com/sublime-merge_build-${SNAPCRAFT_PROJECT_VERSION}_${SNAPCRAFT_TARGET_ARCH}.deb
    plugin: dump
    override-build: |
      snapcraftctl build
      # Correct icon path
      sed -i 's|Icon=sublime-merge|Icon=/opt/sublime_merge/Icon/256x256/sublime-merge.png|' ${SNAPCRAFT_PART_INSTALL}/opt/sublime_merge/sublime_merge.desktop
      # Desktop Action are not Unity specific.
      sed -i 's|OnlyShowIn|#OnlyShowIn|g' ${SNAPCRAFT_PART_INSTALL}/opt/sublime_merge/sublime_merge.desktop
    stage-packages:
      - libbsd0
      - libffi6
      - libgtk-3-0
      - libpcre3
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6
      - libglu1-mesa
    build-attributes:
      - no-patchelf
      
