name: sublime-merge
title: Sublime Merge
version: "2125"
summary: Meet a new Git Client, from the makers of Sublime Text
base: core24
description: |
  Meet a new Git Client, from the makers of Sublime Text.

contact: https://github.com/snapcrafters/sublime-merge/issues
issues: https://github.com/snapcrafters/sublime-merge/issues
website: https://www.sublimemerge.com/
source-code: https://github.com/snapcrafters/sublime-merge
license: Proprietary

platforms:
  amd64:
  arm64:

grade: stable
confinement: classic

# These libraries are discovered at runtime by libGL, GTK, or Sublime Merge.
lint:
  ignore:
    - library:
        - usr/lib/**/libGLX_mesa.so*
        - usr/lib/**/libXxf86vm.so*
        - usr/lib/**/libcurl.so*
        - usr/lib/**/libdconf.so*
        - usr/lib/**/liblber.so*
        - usr/lib/**/libldap.so*
        - usr/lib/**/libnghttp2.so*
        - usr/lib/**/libpsl.so*
        - usr/lib/**/librtmp.so*
        - usr/lib/**/libssh.so*
        - usr/lib/**/libsasl2.so*
        - usr/lib/**/libvulkan.so*
        - usr/lib/**/libxcb-glx.so*

apps:
  sublime-merge:
    command: opt/sublime_merge/sublime_merge
    desktop: usr/share/applications/sublime_merge.desktop

parts:
  sublime-merge:
    source: https://download.sublimetext.com/sublime-merge_build-${CRAFT_PROJECT_VERSION}_${CRAFT_ARCH_BUILD_FOR}.deb
    plugin: dump
    override-build: |
      craftctl default
      # Correct icon path
      sed -i 's|Icon=sublime-merge|Icon=/opt/sublime_merge/Icon/256x256/sublime-merge.png|' ${CRAFT_PART_INSTALL}/usr/share/applications/sublime_merge.desktop
      # Desktop Action are not Unity specific.
      sed -i 's|OnlyShowIn|#OnlyShowIn|g' ${CRAFT_PART_INSTALL}/usr/share/applications/sublime_merge.desktop
    stage-packages:
      - libcurl4t64
      - libgl1
      - libgtk-3-0t64
      - libx11-6
    prime:
      - -usr/lib/*/libcolordprivate.so*
      - -usr/lib/*/libicui18n.so*
      - -usr/lib/*/libicuio.so*
      - -usr/lib/*/libicutest.so*
      - -usr/lib/*/libicutu.so*
    build-attributes:
      - enable-patchelf

  runtime-paths:
    after:
      - sublime-merge
    plugin: nil
    build-packages:
      - patchelf
    override-prime: |
      craftctl default
      patchelf --force-rpath --set-rpath \
        "\$ORIGIN:\$ORIGIN/../../usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}:/snap/core24/current/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}:/snap/core24/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}" \
        "$CRAFT_PRIME/opt/sublime_merge/sublime_merge"
